let techstack = [
    {
        name: 'Laravel',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Laravel.svg/1200px-Laravel.svg.png',
        rowStart: 1,
        colStart: 2,
        rowEnd: 3,
        colEnd: 4,
    },
    {
        name: 'Node.js',
        logo: 'https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg',
        rowStart: 1,
        colStart: 4,
        rowEnd: 3,
        colEnd: 6,
    },
    {
        name: 'Express',
        logo: 'https://expressjs.com/images/express-facebook-share.png',
        rowStart: 1,
        colStart: 7,
        rowEnd: 3,
        colEnd: 9,
    },
    {
        name: 'Vue.js',
        logo: 'https://vuejs.org/images/logo.png',
        rowStart: 3,
        colStart: 8,
        rowEnd: 5,
        colEnd: 10,
    },
    {
        name: 'React',
        logo: 'https://cdn.freelogovectors.net/wp-content/uploads/2018/12/react_logo.png',
        rowStart: 3,
        colStart: 1,
        rowEnd: 5,
        colEnd: 3,
    },
    {
        name: 'JavaScript',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Javascript_Logo.png',
        rowStart: 5,
        colStart: 4,
        rowEnd: 7,
        colEnd: 6,
    },
    {
        name: 'PHP',
        logo: 'https://www.php.net//images/logos/new-php-logo.svg',
        rowStart: 1,
        colStart: 1,
        rowEnd: 2,
        colEnd: 2,
    },
    {
        name: 'Magento',
        logo: 'https://seeklogo.com/images/M/magento-logo-7F3911AE9E-seeklogo.com.png',
        rowStart: 1,
        colStart: 6,
        rowEnd: 2,
        colEnd: 7,
    },
    {
        name: 'MySQL',
        logo: 'https://download.logo.wine/logo/MySQL/MySQL-Logo.wine.png',
        rowStart: 1,
        colStart: 9,
        rowEnd: 2,
        colEnd: 10,
    },
    {
        name: 'MongoDB',
        logo: 'https://infinapps.com/wp-content/uploads/2018/10/mongodb-logo.png',
        rowStart: 2,
        colStart: 9,
        rowEnd: 3,
        colEnd: 10,
    },
    {
        name: 'Composer',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Logo-composer-transparent.png',
        rowStart: 6,
        colStart: 2,
        rowEnd: 7,
        colEnd: 3,
    },
    {
        name: 'npm',
        logo: 'https://raw.githubusercontent.com/npm/logos/master/npm%20logo/npm-logo-red.png',
        rowStart: 5,
        colStart: 1,
        rowEnd: 6,
        colEnd: 2,
    },
    {
        name: 'Docker',
        logo: 'https://www.docker.com/sites/default/files/d8/2019-07/vertical-logo-monochromatic.png',
        rowStart: 2,
        colStart: 1,
        rowEnd: 3,
        colEnd: 2,
    },
    {
        name: 'git',
        logo: 'https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png',
        rowStart: 5,
        colStart: 3,
        rowEnd: 6,
        colEnd: 4,
    },
    {
        name: 'HTML',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/1200px-HTML5_logo_and_wordmark.svg.png',
        rowStart: 6,
        colStart: 6,
        rowEnd: 7,
        colEnd: 7,
    },
    {
        name: 'CSS',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/1200px-CSS3_logo_and_wordmark.svg.png',
        rowStart: 5,
        colStart: 7,
        rowEnd: 6,
        colEnd: 8,
    },
    {
        name: 'LESS',
        logo: 'https://smartcityacademie.nl/wp-content/uploads/2016/03/less-logo.png',
        rowStart: 5,
        colStart: 9,
        rowEnd: 6,
        colEnd: 10,
    },
    {
        name: 'SASS',
        logo: 'https://sass-lang.com/assets/img/styleguide/seal-color-aef0354c.png',
        rowStart: 6,
        colStart: 9,
        rowEnd: 7,
        colEnd: 10,
    },
]

export default techstack